title: Gyanendra Chaubey
#logo: https://github.com/GyanendraChaubey/gyanendrachaubey.github.io/blob/main/assets/imgs/gyan_circle.png
description: Learning@IITJodhpur
#show_downloads: true
theme: jekyll-theme-minimal